name: Build GUI client

on:
  push:
    paths:
      - 'MailDisk-GUI/**'
      - '.github/workflows/buildGUI.yml'
  pull_request:
    paths:
      - 'MailDisk-GUI/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          cd MailDisk-GUI
          nuget restore
          msbuild MailDisk-GUI.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MailDisk-GUI
          path: MailDisk-GUI/MailDisk-GUI/bin/Release
